### ISSUE TITLE
iOS Shared Keychain Support

### ISSUE THREAD

**Issue by tsteele2013** [wkh237/react-native-azure-ad#10]
Azure AD supports keychain sharing on iOS devices, so that if i log into one app using my AD creds, I should be able to login to another app automatically without having to re-enter my credentials. Have you ever been able to implement this using your repository?

**Comment by msardi23** [comment]
Does this work with this package and if so can you provide an example of what is needed to enable this?

**Comment by tsteele2013** [comment]
@msardi23 I wasn't able to find a way to do this using this package, but I did find a workaround. I'm primarily a Swift developer. I used Microsoft's officially supported [AzureAD Library](https://github.com/AzureAD/azure-activedirectory-library-for-objc/tree/master) to write the Auth logic in Swift. Then I used React Native's [Native Module Bridging](http://facebook.github.io/react-native/docs/native-modules-ios.html) to call that Swift code from inside my JS.

It's quite tedious, but SSO works perfectly between my apps.
