### ISSUE TITLE
Get signed in user's email or id information

### ISSUE THREAD

**Issue by sdevalapurkar** [wkh237/react-native-azure-ad#19]
Is there a way to get the signed in user's information, such as the email address they used to log in, or their id credentials or something?

**Comment by wkh237** [comment]
This information should be included in the access_token, you can find them by simply using the BASE64 decoder, you can try this by pasting the `access token` to [JWT.io](https://jwt.io/) there's an online tool for this.

**Comment by sdevalapurkar** [comment]
Beauty! Got it to work, thank you @wkh237 and also thanks for the great package

**Comment by Taewa** [comment]
I use [base-64](https://github.com/mathiasbynens/base64) to decode `access_token` in my React Native project.
