### ISSUE TITLE
Logout Issue

### ISSUE THREAD

**Issue by PratikG9** [wkh237/react-native-azure-ad#21]
https://stackoverflow.com/questions/45568063/not-able-to-logout-from-login-webview-adloginview

**Comment by wkh237** [comment]
try to remove cookies in the domain with [react-native-cookies](https://github.com/joeferraro/react-native-cookies).

**Comment by PratikG9** [comment]
Thank you very much

**Comment by srinivasdamam** [comment]
@PratikG9 are you clearing all the cookies or doing it by name or domain?
I want to clear only cookies set by azure.

**Comment by PratikG9** [comment]
Yes, clearing all the cookies.
