### ISSUE TITLE
Please Publish to npm the latest

### ISSUE THREAD

**Issue by GSingh01** [wkh237/react-native-azure-ad#60]
@wkh237 Kindly publish the latest to npm after merging PRs. Thanks

**Comment by wkh237** [comment]
@GSingh01 I just noticed that my ownership of the package is removed due to the inactivity. In case you need to use the package, I published the latest version `0.2.5` to an individual branch where you can install the version with npm.

**Comment by GSingh01** [comment]
@wkh237 Thanks for quick reply, Upon checking in npm could not locate any package with that version.
