### ISSUE TITLE
Please support prompt= login | none | consent

### ISSUE THREAD

**Issue by Vivihung** [wkh237/react-native-azure-ad#7]
I'm working on iOS react native app. 
In my case, I have to set prompt parameter to consent to be able to get a token.
The error I got without prompt parameter is 
`AADSTS65001: The user or administrator has not consented to use the application with ID 'xxxx-xxxxx-xxxx-xxx'. Send an interactive authorization request for this user and resource. `

There is a [stackoverflow post](http://stackoverflow.com/questions/40109711/the-user-or-administrator-has-not-consented-to-use-the-application-send-an-int) about it.
To know more about prompt, see [here](https://docs.microsoft.com/en-us/azure/active-directory/active-directory-protocols-openid-connect-code).

**Comment by wkh237** [comment]
@Vivihung , thanks for the information. I'll merge you PR and publish a new release to NPM 👍

**Comment by wkh237** [comment]
Already publish to NPM, [here's](https://github.com/wkh237/react-native-azure-ad/releases/tag/v0.2.2) the release. 😃
